#!/bin/bash
#
if git rev-parse --verify HEAD >/dev/null 2>&1   #
then  #
against=HEAD~  #
else #
# Initial commit: diff against an empty tree object
against=4b825dc642cb6eb9a060e54bf8d69288fbee4904  #
fi  #
#
git diff --cached --name-only $against > Changed_Files
#
echo >&2 $(date): Changed Files - $(cat Changed_Files)
sourceanalyzer -b local_build -clean
echo >&2 $(date): Generating Build with list of files...
sourceanalyzer -b local_build $(cat Changed_Files) -exclude "node_modules"
echo >&2 $(date): Fortify Scanning Starts..
powershell.exe -ExecutionPolicy Bypass -Command 'c:\Tools\SCA\hooks\pwsfortify.ps1'
echo >&2 $(date): Fortify Analyzing Completed... #
#
if [[ $(cat fortify_result.txt) == *"No issues matched"* ]]; then #
  echo >&2 $(date): No Fortify Vulnerabilities Found!!! #
  exit 0 #
fi #
#
if [[ $(cat fortify_result.txt) == *"[Error]"* ]];then           #
  echo >&2 $(date): There is no valid files to scan!!!           #
  exit 0          #
fi          #
#
echo >&2 $(date): Fortify Vulnerabilities Found!!!          #
         #
u=`id -u -n`          #
echo >&2 "logged User id  $u"          #
#
result=$(curl -X GET --header "Accept: */*" "https://vzsca.ebiz.verizon.com/api/v1/getExemptionFlag/$u" )
echo >&2 "Exemption : " $result         #
	if [[ $result == *"Yes"* ]]; then         #
		 echo >&2 $(date): Commit are exempted..!!!		         #
		 exit 0         #
	fi         #
echo >&2 Issues Summary - $(tail -n 20 fortify_result.txt)
echo >&2 ===========================================================================================
echo >&2 $(date): Please contact help-sca channel for support
echo >&2 $(date): For more information, please visit https://oneconfluence.verizon.com/display/SCA!!!
echo >&2 ===========================================================================================
exit 1 #